// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAuSv7WPafztHNrSNj3WHxVQ1HZzvkHas',
    appId: '1:317313188938:web:651d0943e67044353512b3',
    messagingSenderId: '317313188938',
    projectId: 'chatzzipt',
    authDomain: 'chatzzipt.firebaseapp.com',
    databaseURL: 'https://chatzzipt-default-rtdb.firebaseio.com',
    storageBucket: 'chatzzipt.appspot.com',
    measurementId: 'G-GQ5W059SZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrJXK4b9p1l9MZ-2oiCkolQxvCYFow4c',
    appId: '1:317313188938:android:a6ac16629f14e49e3512b3',
    messagingSenderId: '317313188938',
    projectId: 'chatzzipt',
    databaseURL: 'https://chatzzipt-default-rtdb.firebaseio.com',
    storageBucket: 'chatzzipt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM9ehpCsL-erfsSuPDxFBpUTgzhrOuH-c',
    appId: '1:317313188938:ios:c3249b51f54de8b93512b3',
    messagingSenderId: '317313188938',
    projectId: 'chatzzipt',
    databaseURL: 'https://chatzzipt-default-rtdb.firebaseio.com',
    storageBucket: 'chatzzipt.appspot.com',
    androidClientId: '317313188938-m9sf5u0ipc26pkg7lkg4fphhrni0jt7b.apps.googleusercontent.com',
    iosClientId: '317313188938-qsp5k4gjpnlu3kpbusbukknm2snvf5ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgptCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM9ehpCsL-erfsSuPDxFBpUTgzhrOuH-c',
    appId: '1:317313188938:ios:c3249b51f54de8b93512b3',
    messagingSenderId: '317313188938',
    projectId: 'chatzzipt',
    databaseURL: 'https://chatzzipt-default-rtdb.firebaseio.com',
    storageBucket: 'chatzzipt.appspot.com',
    androidClientId: '317313188938-m9sf5u0ipc26pkg7lkg4fphhrni0jt7b.apps.googleusercontent.com',
    iosClientId: '317313188938-qsp5k4gjpnlu3kpbusbukknm2snvf5ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgptCourse',
  );
}
